# Generated by Django 5.2.5 on 2025-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('weakness', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads')),
            ],
        ),
    ]
