# Generated by Django 5.2.5 on 2025-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
